SRC/app/models/funcionario_model.py
'''Docstring'''
# pylint: disable = C0103, R0903

from sqlalchemy_utils import ChoiceType
from app import db
# from Funcionario import Funcionario


class func_model(db.Model):
    '''Docstring'''
    __tablename__ = 'Funcionarios'

    SEXO_CHOICES = [
        ('M', 'Masculino'),
        ('F', 'Feminino')
    ]

    id = db.Column(db.Integer, primary_key=True, autoincrement=True)
    nome = db.Column(db.String(50))
    sexo = db.Column(ChoiceType(SEXO_CHOICES))
    data_nasc = db.Column(db.DateTime)
    cpf = db.Column(db.String(100), unique=True)
    empresa = db.Column(db.String(50))
    cargo = db.Column(db.String(50))
    email = db.Column(db.String(200), unique=True)

    def teste(self):
        '''docstring'''

SRC/app/forms/funcionario_form.py
'''docstring'''
# pylint: disable=C0103

from flask_wtf import FlaskForm
from wtforms import StringField, DateField, SelectField
from wtforms.fields import EmailField
from wtforms.validators import DataRequired, Email
DATE_INPUT_FORMATS = ['%d-%m-%Y', '%Y-%m-%d']


class funcionario_Form(FlaskForm):
    '''docstring'''
    nome = StringField("nome", validators=[DataRequired()])
    email = EmailField("email", validators=[Email(), DataRequired()])
    data_nasc = DateField("data_nasc", validators=[
                          DataRequired()])
    sexo = SelectField("sexo", validators=[DataRequired()],
                       choices=[('F', 'Feminino'), ('M', 'Masculino')])
    empresa = StringField("empresa", validators=[DataRequired()])
    cpf = StringField("cpf", validators=[DataRequired()])
    cargo = StringField("cargo", validators=[DataRequired()])

SRC/app/__init__.py
''' documentation'''
# pylint: disable= C0413, C0103

from flask import Flask
from flask_sqlalchemy import SQLAlchemy
from flask_migrate import Migrate
from flask_wtf import CSRFProtect
from flask_babel import Babel


app = Flask(__name__)

app.config.from_object('config')

# engine   = create_engine(SQLALCHEMY_DATABASE_URI)
db = SQLAlchemy(app)
migrate = Migrate(app, db)
csrf = CSRFProtect(app)
csrf.init_app(app)

#ativando pacote de traducao do erros
babel = Babel(app)

from .models import funcionario_model
# from .views import cadastro_func
# from .views import perfil_view

SRC/app/views/Funcionarios.py
'''
    Docstring
'''
# pylint: disable = C0103
import datetime
from flask import Blueprint, render_template, redirect, url_for
from Funcionario import Funcionario
from app.forms import funcionario_form
from app.models import funcionario_model
from app import db

# from app import app

cadastro_func_blueprint = Blueprint('cadastro', __name__)
listar_func_blueprint = Blueprint('funcionarios', __name__)
editar_func_blueprint = Blueprint('editar', __name__)

# Página passando valor default ou passando variavel pela rota
# @cadastro_Func_blueprint.route('/')
# @cadastro_Func_blueprint.route('/menufunc/', defaults={'nome': None})
# @cadastro_Func_blueprint.route('/menufunc/<string:nome>')
# def cadastro_func(nome):
#     ''' Docstring'''
#     if nome:
#         return render_template('menuCadastro.html', nome=nome)
#     return render_template('menuCadastro.html', nome='Nome Funcionario')


# @cadastro_add_blueprint.route('/menufunc/addfunc/', methods=['GET', 'POST'])
# def cadastro_add():
#     ''' Docstring'''
#     if request.method == 'POST':
#         newfunc = Funcionario(request.form['empresa'])
#         newfunc.set_nome(request.form['nome'])
#         newfunc.set_cpf(request.form['cpf'])
#         # empresa = request.form['empresa']
#         # funcao = request.form['funcao']
#         print([newfunc.get_nome(), newfunc.get_cpf()])
#         # return f'<h1> nome: {nome}</h1> <h1> CPF: {cpf}</h1>'
#         # return redirect('/menufunc/')
#         return redirect(url_for('menufunc.cadastro_func'))
#     return render_template('cadastro_add.html')

@listar_func_blueprint.route('/funcionarios/', defaults={'idd': None}, methods=['GET', 'POST'])
@listar_func_blueprint.route('/funcionarios/<int:idd>/')
def listar_func(idd):
    '''docstring'''
    if idd is not None:
        print(idd)
        func = funcionario_model.func_model.query.filter_by(id=idd).first()
        # func.data_nasc = datetime.date.strftime(func.data_nasc, "%d/%m/%Y")
        return render_template("funcionarios/func_perfil.html/", funcionarios=func)
    func = funcionario_model.func_model.query.all()
    return render_template("/funcionarios/func_cadastrados.html/", funcionarios=func)


@editar_func_blueprint.route("/funcionarios/editar/<int:idd>/", methods=['GET', 'POST'])
def editar_func(idd):
    '''docstring'''
    func = funcionario_model.func_model.query.filter_by(id=idd).first()
    form = funcionario_form.funcionario_Form(obj=func)
    if form.validate_on_submit():
        editfunc = Funcionario(form.empresa.data)
        editfunc.set_nome(form.nome.data)
        editfunc.set_sexo(form.sexo.data)
        editfunc.set_data_nasc(form.data_nasc.data)
        editfunc.set_cpf(form.cpf.data)
        editfunc.set_empresa(form.empresa.data)
        editfunc.set_cargo(form.cargo.data)
        editfunc.set_email(form.email.data)

        func.nome = editfunc.get_nome()
        func.sexo = editfunc.get_sexo()
        func.data_nasc = datetime.date.strftime(
            editfunc.get_data_nasc(), "%d/%m/%Y")
        func.cpf = editfunc.get_cpf()
        func.empresa = editfunc.get_empresa()
        func.cargo = editfunc.get_cargo()
        func.email = editfunc.get_email()

        try:
            db.session.commit()
        except NameError as db_error:
            print(f"cliente nao foi editado no BD type:{db_error}")
        return redirect(url_for('funcionarios.listar_func'))
    return render_template("/funcionarios/form.html", form=form)


@cadastro_func_blueprint.route("/funcionarios/cadastrar_func/", methods=['GET', 'POST'])
def cadastrar_func():
    '''docstring'''
    form = funcionario_form.funcionario_Form()
    if form.validate_on_submit():
        newfunc = Funcionario(form.empresa.data)
        newfunc.set_nome(form.nome.data)
        newfunc.set_sexo(form.sexo.data)
        newfunc.set_data_nasc(form.data_nasc.data)
        newfunc.set_cpf(form.cpf.data)
        newfunc.set_empresa(form.empresa.data)
        newfunc.set_cargo(form.cargo.data)
        newfunc.set_email(form.email.data)

        data_formatada = datetime.date.strftime(
            newfunc.get_data_nasc(), "%d/%m/%Y")

        func = funcionario_model.func_model(
            nome=newfunc.get_nome(), sexo=newfunc.get_sexo(),
            data_nasc=data_formatada, cpf=newfunc.get_cpf(),
            empresa=newfunc.get_empresa(), cargo=newfunc.get_cargo(),
            email=newfunc.get_email())
        try:
            db.session.add(func)
            db.session.commit()
        except NameError as db_error:
            print(f"cliente nao foi cadastrado no BD type:{db_error}")
        return redirect(url_for('funcionarios.listar_func'))
    return render_template('/funcionarios/form.html', form=form)

SRC/app/views/usuarios_view.py
'''docstring'''

from flask import Blueprint, render_template
# from app import app

usuarios_blueprint = Blueprint('usuarios', __name__)


@usuarios_blueprint.route('/usuarios/')
def lista_usuarios():
    '''docstring'''
    return render_template('usuarios_temp.html')


@usuarios_blueprint.route('/usuarios/settings/')
def usuarios_settings():
    '''docstring'''
    return render_template('usuarios_settings.html')

SRC/app/templates/cadastro_add.html
<!DOCTYPE html>
<html>
    <head>
        <meta charset="utf-8" />
        <title>Menu Cadastro</title>
        <link rel="stylesheet" href="{{ url_for('static', filename='css/bootstrap.css')}}">

    </head>
    <body>
        <h1>Cadastrar Funcionário:</h1>
        <form method="post">
            <label for="nome">Nome:</label>
            <input type="text" id="nome" name="nome"/> <br>
            <label for="cpf">CPF:</label>
            <input type="text" id="cpf" name="cpf"/> <br>
            <label for="cpf">Empresa:</label>
            <input type="text" id="empresa" name="empresa"/> <br>
            <label for="cpf">Função:</label>
            <input type="text" id="funcao" name="funcao"/> <br>
            <br>
            <input type="submit" value="submit">
        </form>
    </body>
</html>

SRC/app/templates/funcionarios/base.html
<!DOCTYPE html>
<html>
    <head>
        <title>
            {% block titulo %}

            {% endblock titulo %}
        </title>
        <meta charset="utf-8" />
        <link rel="stylesheet" href="{{ url_for('static', filename='css/bootstrap.css')}}">
    </head>
    <body>
        <main class="container">
            {% block conteudo %}
        
            {% endblock conteudo %}
        </main>
    </body>
</html>

SRC/app/templates/funcionarios/form.html
{% extends "/funcionarios/base.html" %}

{% block titulo %}
Cadastro de Funcionarios
{% endblock titulo %}

{% block conteudo %}
<h1>Formulario de Cadastro</h1>
<form method="post">
    {{ form.csrf_token }}
    <div class="form-group">
        <label>Nome: </label>
        {{ form.nome (class='form-control') }}

        {% if form.errors.nome %}
        <div class="alert alert-danger">
            {{ form.errors.nome }}
        </div>
        {% endif %}
        
    </div>
    <div class="form-group">
        <label>Sexo: </label>
        {{ form.sexo (class='form-control')}}
        {% if form.errors.sexo %}
        <div class="alert alert-danger">
            {{ form.errors.sexo }}
        </div>
        {% endif %}
    </div>
    <div class="form-group">
        <label>Data de Nascimento: </label>
        {{ form.data_nasc (class='form-control')}}
        {% if form.errors.data_nasc %}
        <div class="alert alert-danger">
            {{ form.errors.data_nasc }}
        </div>
        {% endif %}
    </div>
    <div class="form-group">
        <label>CPF: </label>
        {{ form.cpf (class='form-control')}}
        {% if form.errors.cpf %}
        <div class="alert alert-danger">
            {{ form.errors.cpf }}
        </div>
        {% endif %}
    </div>
    <div class="form-group">
        <label>Empresa: </label>
        {{ form.empresa (class='form-control')}}
        {% if form.errors.empresa %}
        <div class="alert alert-danger">
            {{ form.errors.empresa }}
        </div>
        {% endif %}
    </div>
    <div class="form-group">
        <label>Cargo: </label>
        {{ form.cargo (class='form-control')}}
        {% if form.errors.cargo %}
        <div class="alert alert-danger">
            {{ form.errors.cargo }}
        </div>
        {% endif %}
    </div>
    <div class="form-group">
        <label>Email: </label>
        {{ form.email (class='form-control')}}
        {% if form.errors.email %}
        <div class="alert alert-danger">
            {{ form.errors.email }}
        </div>
        {% endif %}
    </div>
    <br><br>
    <button class="btn btn-primary" type="submit">Cadastrar</class></button>
</form>

{% endblock conteudo %}

SRC/app/templates/funcionarios/func_cadastrados.html
{% extends "/funcionarios/base.html" %}

{% block titulo %}
Cadastro de Funcionarios
{% endblock titulo %}

{% block conteudo %}
<h1>Gestão de Funcionários</h1>
<table class="table">
    <thead>
        <tr>
            <th>Nome</th>
            <th>Empresa</th>
            <th>Cargo</th>
            <th>Ações</th>
        </tr>
    </thead>
    <tbody>
        {% for i in funcionarios %}
        <tr>
            <td><a class="link-offset-2 link-underline link-underline-opacity-0" 
                href="{{ url_for('funcionarios.listar_func', idd=i.id)}}">{{i.nome}}</a>
            </td>
            <td>{{i.empresa}}</td>
            <td>{{i.cargo}}</td>
            <td>
                <a class="link-offset-2 link-underline link-underline-opacity-0" 
                href="{{ url_for('editar.editar_func', idd=i.id)}}">Editar</a>
                <a href="#">Remover</a>
            </td>
        </tr>
        {% endfor %}
    </tbody>
</table>

{% endblock conteudo %}

SRC/app/templates/funcionarios/func_perfil.html
{% extends "funcionarios/base.html" %}

{% block titulo %}
Perfil do Funcionario
{% endblock titulo %}

{% block conteudo %}
<div class="card">
    <div class="card-header">
        <h5>Dados do Funcionario</h5>
        <div class="container mt-5">
            <div class="card">
            <div class="row g-0">
                <!-- Left Side: Profile -->
                <div class="col-md-8">
                <div class="card-body">
                    <div class="d-flex align-items-center">
                    <img src="/static/img/avatar_profile_geral.png" alt="Profile Image" class="profile-img me-3" style="width:25%">
                        <div class="row">
                            <h5 class="card-title">{{funcionarios.nome}}</h5><br>
                            <div class="col">
                                <p class="card-text"><b>Sexo: </b>{{funcionarios.sexo}}</p>
                                <p class="card-text"><b>CPF: </b> {{funcionarios.cpf}}</p>
                            </div>
                            <div class="col">
                                <p class="card-text"><b>Empresa: </b> {{funcionarios.empresa}}</p>
                                <p class="card-text"><b>Data de Nascimento: </b> {{funcionarios.data_nasc.strftime("%d/%m/%Y")}}</p>
                            </div>
                            <div class="col">
                                <p class="card-text"><b>Cargo: </b> {{funcionarios.cargo}}</p>
                                <p class="card-text"><b>Email: </b> {{funcionarios.email}}</p>
                            </div>
                            <!--<p class="card-text"><small class="text-muted">Last updated 3 mins ago</small></p>-->
                        </div>
                    </div>
                </div>
                </div>
            </div>
            </div>
        </div>
    </div>
</div>
{% endblock conteudo %}

SRC/app/templates/usuarios_settings.html
<!DOCTYPE html>
<html>
    <head>
        <title>Nome da página</title>
        <meta charset="utf-8" />

    </head>
    <body>
        <a href="BasicoHTML.html">Basico do HTML</a>
    </body>
</html>

SRC/app/templates/usuarios_temp.html
<!DOCTYPE html>
<html>
    <head>
        <title>Nome da página</title>
        <meta charset="utf-8" />

    </head>
    <body>
        <a href="BasicoHTML.html">Basico do HTML</a>
    </body>
</html>